### ISSUE TITLE
Use `pageAction` instead of `browserAction`?

### ISSUE THREAD

**Issue by timnew** [zalmoxisus/redux-devtools-extension#1]
@zalmoxisus Do you think it would be nicer it the extension is registered as `pageAction` instead of `browserAction`. Since we only use it in particular pages instead of every one. 

Before the extension can recognize the redux store, we can use it as a permanent page action(displayed on every page)?

**Comment by zalmoxisus** [comment]
Yes, good suggestion. Will implement this when we'll have an option page as well, where we may indicate for which pages to use it.

**Comment by timnew** [comment]
I have a suggestion, how about this:

1. We disable the `page action` by default.
2. We can inject the `devToolsExtension` to `window` object with content script on every page.
3. Then we can when the devToolExtension is invoked, then we can send a message to backend script via `sendMessage`
4. When the backend script received the message, then it enable the pageAction for the tab that sent the message(we can get the tab id in the `message sender`).

Then the extension have the capability to know when it should be enabled.

**Comment by timnew** [comment]
I check the code, I think the only block is that the store is a singleton in the extension.
So it might be a problem if we are debugging multiple tabs with the extension simultaneously.
But I think it can be fixed, if we monitor the tab lifecycle events?!

**Comment by zalmoxisus** [comment]
Yes, it is a good solution, but we also need to enable/disable specific urls explicitly, for example in production (instead of disabling/enabling the extension).

**Comment by timnew** [comment]
Hmm, sorry I missed this part.

I imagine that we could use Dan's [multiple file solution](https://github.com/gaearon/redux-devtools/issues/166#issuecomment-150049338).

But anyway,  we restrict the behavior against specific url, then we can avoid to inject content script to every tab. Instead, we use [`declarative web request`](https://developer.chrome.com/extensions/declarativeWebRequest) to inject `content script` on demand.

Only when the url matches the criteria, the `devToolsExtension` is injected. It also avoid the potential security issue.

**Comment by zalmoxisus** [comment]
Thanks, @timnew! It is much better with a pageAction.

If you want to test it before the next release, just run `npm run build:extension`.

About debugging multiple tabs, it's the same as for the browserAction. The popup/window's store is updated if you open/refresh the page or dispatch an action, otherwise you have their the devtools for the last active tab (as in demo). I'm not sure whether it is a bug or a feature, but I found it useful. If someone wants to have there only the devtools for the current tab, just file and issue, it is easy to fix.

**Comment by zalmoxisus** [comment]
Fixed the issue with multiple tabs in https://github.com/zalmoxisus/redux-devtools-extension/commit/49b52988b82047fa833a7b760fb0343f0c1e60dd.

**Comment by timnew** [comment]
awesome, I was thinking maybe I can provide a pull request later today.

I'll try latest release today!

Cheers,
Tim

**Comment by zalmoxisus** [comment]
Feel free to reopen the issue if something goes wrong.
Opened another issue for the option page: #3.

**Comment by timnew** [comment]
Got it. Do you have any idea about how to build options page? Redux + React?

Actually, the stuff I'm building with redux and react is the option page for a chrome extension. :joy:

**Comment by zalmoxisus** [comment]
It's as easy as an browser/page action page. I do not see nothing special. Just would be great to choose a React lib for the forms' UI. And of course, we need to save the configuration to chrome.storage.sync and read it from the content script or receive it from the background script. The latter would be preferable (though more complicated) as to be compatible with Firefox (because firefox extensions do not have access to chrome.storage from the content script).

**Comment by zalmoxisus** [comment]
If you found something different in the option page, we may add it in [our boilerplate](https://github.com/zalmoxisus/browser-redux).

**Comment by timnew** [comment]
Sure!

I might need to get familiar with FF `web extension` first. I have no experience about it before. As you mentioned, there is some minor differences might impact on the implementation.
