### ISSUE TITLE
Fix memory usage to not deplete available memory and crash

### ISSUE THREAD

**Issue by iki** [zalmoxisus/redux-devtools-extension#115]
With our client redux app, after opening the extension window, it quickly takes 1-2gb memory and crashes.

Happens with both the Log Monitor and Inspector.

Happens with both the version from google webstore, and manually built current master.

Related subissues:
1. The app tab allocated memory is going up and down too. Is it because of open dev tools (console)?
2. When the extension window is closed, the memory is not deallocated, until the extension is reloaded,
3. When the app tab is closed, the memory is not deallocated either.

Would it be possible to
1. Minimize memory usage, esp. to not copy any app store data?
2. Allow disabling the dev tools integration?
3. Free respective memory on closing either the extension window or the app window?

**Comment by zalmoxisus** [comment]
Hey @iki, 

Thanks for the detailed report!

> 2. Free memory on closing the extension window?

I did a profiling and indeed there's a memory leak. Due to the fact that the monitor's window's listeners was subscribing to background's redux store, garbage collector failed to free anything when window is closed.

Fixed in `v1.3.1` by implementing subscribing through messages. Also I transformed the background page into an event page, so now when the extension becomes inactive (extension's windows and app's tabs are closed) it will no occupy any memory at all. Just wait several seconds.

Please give it a try!

**Comment by zalmoxisus** [comment]
> Minimize memory usage, esp. to not copy any app store data?

This one should be addressed to [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument). The problem is that for every stored action there you add the current state. So, if there's a big object in your state and you have `maxAge` set to `50` (which is by default for the extension) it will be stored 50 times in the liftedState. If you have any ideas how to optimize that, it would be more than welcome.

When you start monitoring (open the extension window), the liftedState is serialized (which is a slow operation for big objects, and most probably it is crashing here in your case) an being sent to the extension's script. The only optimization from the extension side is to set `Actions history limit` to a lower value or to disable serialization (in case you don't use ImmutableJs and don't have circular references), which should be on the options page (in settings).

**Comment by zalmoxisus** [comment]
@iki, please reopen the issue if you're still facing the problem with memory leaks.

Also, in `v1.4` you can filter big datas like in the [example](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v1.4.0).
