### ISSUE TITLE
[Question] Multiple stores on same page

### ISSUE THREAD

**Issue by yarcub** [zalmoxisus/redux-devtools-extension#121]
Is it possible to enhance multiple stores on the same page? For example, having a dependency that also uses redux for internal state management and being able to switch between both on dev tools.

I thought the instance `name` on the `config` was to support that use case, but doesn't seem to work like that. Any hints?

**Comment by zalmoxisus** [comment]
It's not supported yet, as we're using tab id as the instance id, as the result the latest store overrides everything else. That said, by instances we mean different tabs.

For now you can use [Remote Redux DevTools](https://github.com/zalmoxisus/remote-redux-devtools), which creates a new connection for every store, an you'll get all the instances there.

**Comment by zalmoxisus** [comment]
Starting from `2.0` the extension [supports multiple stores in one page](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.0). Feel free to reopen this issue if you experience any troubles with that.

**Comment by steppefox** [comment]
I had i problems with that (2h of dancing around), till I checked link above. My problem was in `instanceId`, without it in the config params for both stores, second store rewrote first store =(( 

Also, could you please update Readme with information about multiple stores? Or I could do it and make a pr =)

**Comment by zalmoxisus** [comment]
@steppefox it should work without that. Maybe we broke that when implemented persisting, `instanceId` is not random because of that. I'll check it out, strange that nobody reported it before.

**Comment by steppefox** [comment]
@zalmoxisus wow, such fast response o_O Thanks for the answer. Little details: first store loading from current app, second store is loading after few seconds from the iframe. Maybe it would help.

**Comment by zalmoxisus** [comment]
@steppefox, that's the case. In order to be able to persist the state (on reloading the page), [`instanceId` is the index of the store by default](https://github.com/zalmoxisus/redux-devtools-extension/pull/276/commits/2f07780e8a41f0af54e50377a2f39374f07d6f9f), which would work for multiple stores on the same page. In case of iframes, both of the stores has `1` as `instanceId`. For running the app in multiple tabs we're using also the tabId. I guess in the same way we could use `frameId` to fix that.

**Comment by zalmoxisus** [comment]
@steppefox, there were also other issues with multiple frames, like orphaned connections. I've just published `2.13.0` on Chrome Store, which includes the fix. However, there will not be possible to persist states for multiple frames, since Chrome generates a new frame id on every page reload. We could provide later some strategies for persisting, like by instanceId or by url.
