### ISSUE TITLE
Not supported Electron

### ISSUE THREAD

**Issue by jhen0409** [zalmoxisus/redux-devtools-extension#13]
The #12 is great work, but It still is not work in Electron. :\

Maybe related to [this doc](https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md#background-pages).
"Currently Electron doesn't support the background pages feature in Chrome extensions"

**Comment by zalmoxisus** [comment]
Hey, @jhen0409.

Thanks for the report! I didn't test with Electron, will do next days.
Despite that restriction, I think the script from electron apps should send messages. The problem could be that the extension is not allowed to receive them.

**Comment by zalmoxisus** [comment]
Unfortunately, it will not be possible to get it work.
Electron supports Chrome extensions, but [doesn't support background pages feature](http://electron.atom.io/docs/latest/tutorial/devtools-extension/#background-pages).
Due to Chrome extension limitations, the script from devpanel cannot communicate with the content script (it can only do eval), so we communicate via background script.
