### ISSUE TITLE
Extension Ignores Redux-Saga

### ISSUE THREAD

**Issue by Sinistralis** [zalmoxisus/redux-devtools-extension#133]
I might be missing something, but it seems like this extension is completely oblivious to Redux-Saga.

https://gist.github.com/Sinistralis/2b181bae168a556b268fd69c32b5f556

It ignores all actions dispatched by Sagas, and if you dispatch an action through the dispatch window in the extension, your Sagas never receive it.

**Comment by zalmoxisus** [comment]
[Starting from `v0.10.0`](https://github.com/yelouafi/redux-saga/releases/tag/v0.10.0), there's a `sagaMiddleware.run(saga, ...args)` which start sagas. 

I added a workaround by [updating the store](https://github.com/zalmoxisus/redux-devtools-extension/commit/0757dac4c2eb217d7bbb8be738d8bae32ec21d86). It should work better with new Redux 4 API.

Please [build the extension](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension) to use it.

**Comment by Sinistralis** [comment]
This makes a lot of sense.  I am running my sagas but was not aware there was context I needed to update in the extension. I'll try this today and get back to you.

**Comment by zalmoxisus** [comment]
Should work in [v2.0.1](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.0.1). Feel free to reopen the issue if it doesn't work.

**Comment by Sinistralis** [comment]
Nah this worked perfectly. Thanks!

**Comment by jayphelps** [comment]
@zalmoxisus This also affected redux-observable https://github.com/redux-observable/redux-observable/issues/81 so I'm trying to understand why. It doesn't modify the store in any way other than the intrinsic way that redux composes middleware to create the store you receive, so this seems like something that shouldn't be a problem since this is normal middleware behavior.

Is there any way we can mitigate this so that it "just works" without the need to `updateStore()`? Admittedly, I don't exactly understand how the devtools hooks into the store so I'm missing a large chunk of context, just coming from a DevEx perspective.

**Comment by jayphelps** [comment]
> Should be fixed after reactjs/redux#1702 gets merged. -@zalmoxisus https://github.com/redux-observable/redux-observable/issues/81#issuecomment-234357231

Nevermind 😄

**Comment by zalmoxisus** [comment]
[The script is pretty simple](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js). Maybe you see a way to overcome that. I don't :(

**Comment by zalmoxisus** [comment]
The extension API was changed. No need for `window.devToolsExtension.updateStore` workaround anymore. Just use `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` or [import `redux-devtools-extension` npm package](https://github.com/zalmoxisus/redux-devtools-extension#13-use-redux-devtools-extension-package-from-npm).
