### ISSUE TITLE
Lots of actions makes browser to freeze

### ISSUE THREAD

**Issue by ondrejbartas** [zalmoxisus/redux-devtools-extension#14]
Hi in my project we are dispatching action after every key stroke in text field which generates tens of actions.

It is impossible to work, because you need to commit changes after few second of using, when you commit them application works as expected.

I had same problem with Redux devtools which was show on page.

When I hide redux devtools  panel it was working perfectly fine. But With your extension it seems that you are rendering all content in popup every time action is dispatched. This is no problem, but can you do that only if popup is shown?

**Comment by ondrejbartas** [comment]
Sorry maybe it is not problem with number of actions but with size of store. Because every action is showing full store tree.

**Comment by zalmoxisus** [comment]
Hi! Yes, the problem should be that every time an action is dispatched, the lifted store data (`store.liftedStore.getState()`) is serialized and sent to the background, then there is parsed to an object again. It was made in order to solve the issue #5. The lifted store, except all your states, contains also the whole history, so it is big enough. I'll try to make an workaround to catch only new states via a store enhancer and sync only them, but still not sure it would be possible without hacking devtools internally.
AFAIK, Chrome popup is loaded only when you open it, so the rerendering shouldn't be a problem. Anyway I'll test it to.

**Comment by zalmoxisus** [comment]
Also, it would be useful to add the ability to disable serialization, so if you do not have circular references, you may boost the performance.

**Comment by gaearon** [comment]
>I had same problem with Redux devtools which was show on page

Which version? There are big perf improvements in 3.0 beta compared to 2.x. Maybe you'd want to check it out.

**Comment by ondrejbartas** [comment]
I am using 3.1. I had same issue with normal devtools I injected to page, It was slow only when devtools were opened (shown) if they were hidden, It was working perfectly fine. 

Is possible to just don't render devtools when popup is not shown?

**Comment by zalmoxisus** [comment]
Hey, @ondrejbartas. I guess @gaearon asked about the version of "normal devtools" you used. The current extension version is 0.3.1.

The action page (popup) is frozen when it is hidden. When you click to the button it is reloaded by Chrome.

The problem here is that due to Chrome extension limitations, neither action page nor Chrome devtools "(from devpanel) cannot communicate with your page directly. That's why we relay all the lifted store changes to the extension background script all the time, and from there the extension pages can get actual states. Because of the seriaizations it is an expensive operation, but I didn't face any performance issue as my states objects aren't so complex.

The good news is that I've came out with a solution for you. I added an option page, where you can specify the delay of the states relaying. By default it is `1` second, so if you have a lot of actions in a second, they will be collected and send and rendered to the devtools all together. You may increase this delay or set to 0 to disable any delay as it was before. Also there's a second option to disable serialization if you states are plain objects. In this case, the first will indicate how often to rerender the devtools.

I'll do more tests and will publish the new release to Chrome store by tomorrow, but you may get it work it now. Just build the extension as indicated in [README](https://github.com/zalmoxisus/redux-devtools-extension#1-get-the-extension). On the extensions page (`chrome://extensions/`), bellow the extension name, you'll find an 'Options' link.

**Comment by zalmoxisus** [comment]
To make it better, we'll go further and limit the number of last actions to be shown in devtools. Otherwise, sooner or later it will be impossible to process a huge amount of data. I don't think it makes lots of sense to have the history of thousands of actions. Does it? Having, let's say, only the last 100 actions should be ok, but of course it will be configurable in the options page.

**Comment by zalmoxisus** [comment]
Hey,
The new version is on Chrome store. The instruction on how to better customize it can be found in [README](https://github.com/zalmoxisus/redux-devtools-extension#how-to-make-it-faster). Let me know whether it works for you.

**Comment by zalmoxisus** [comment]
Tested with a complex store with concurrent actions, and works smoothly now.

**Comment by ondrejbartas** [comment]
good job, I have tested it too and i didn't get any problem with speed.
