### ISSUE TITLE
Replay mode

### ISSUE THREAD

**Issue by amannn** [zalmoxisus/redux-devtools-extension#140]
First of all, really great work on this extension! I use it almost daily when working on Redux apps.

I'm encountering an issue, when using the time travel feature of the dev tools. The problem mostly comes down to a view reacting to a state change and dispatching another action. The problem is pretty well described in [issue 167 from redux-devtools](https://github.com/gaearon/redux-devtools/issues/167).

I was wondering if this could somehow be solved by this extension?

I guess there should be some kind of replay mode that is entered when the action history is changed through the dev tools. As redux-devtools-extension is injected as a store enhancer, would it be possible to prevent new actions reaching the reducers? Otherwise, maybe a dev tools middleware could be added that has this behaviour?

Thanks!

**Comment by zalmoxisus** [comment]
This should be implemented in [`redux-devtools-instrment`](https://github.com/zalmoxisus/redux-devtools-instrument), but only after Redux 4.0 with [new API for store enhancers](https://github.com/reactjs/redux/pull/1702) is released. A possible solution was [suggested](https://github.com/gaearon/redux-devtools/pull/263) before.

**Comment by rybon** [comment]
My suggestion would be to make the rendering itself not cause any side effects. A render is basically always triggered by a dispatch and having another dispatch triggered as a result of that seems wrong. Before you know it, you have a cascade of state mutations and / or side effects going off from a single dispatch and you'll lose track of which dispatch caused what. It will also make things hard to test. This problem is what made large Backbone applications hard to manage.

React and Redux are designed to get away from that. In the Redux render loop there is only one event (change) and only one subscriber (React). To keep that contract for rendering intact, I would not trigger any dispatch in a life cycle method of React (or React Router). Instead, have a look at Redux Saga or something similar.

**Comment by zalmoxisus** [comment]
Implemented in `v2.3.0`. See [the description](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.3.0) and [the example of usage](https://github.com/zalmoxisus/redux-devtools-extension/commit/352f0797f041866cf1d73ed5bf1008a6096813ea).

**Comment by amannn** [comment]
Looks great! Are you planning use the `isTimeTraveling` feature in the chrome extension for the slider monitor?

**Comment by zalmoxisus** [comment]
@amannn, yes, it is used for side effects to disable them when time traveling. See #145 for more details.

**Comment by ccorcos** [comment]
@zalmoxisus it would be great if we could import just an array of actions. the states should be reproducible and this way, we could save tracking data thats captured from elsewhere and replay exactly what happened. how does that sound to do? I'm happy to help!

**Comment by zalmoxisus** [comment]
@amannn, there's a better way now to prevent side effects like those while time travelling. It will also help to lock changes for the us case of @ccorcos.  [See the post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) for details on how to get it.
