### ISSUE TITLE
Latest version crashes our app

### ISSUE THREAD

**Issue by yanivtal** [zalmoxisus/redux-devtools-extension#15]
JS error 
```Uncaught DataCloneError: Failed to execute 'postMessage' on 'Window': An object could not be cloned.```
Somewhere around window.postMessage({payload:o.serialize?a["default"](n)

We have to uninstall the extension until this is fixed.

**Comment by zalmoxisus** [comment]
Thanks for the report. We made serialization optional in the new version. It is enabled by default, but it seems that the options values come later than the first "@@INIT" action. I will fix it ASAP.

BTW, instead of uninstalling it, you may just disable the extension or exclude your url from being injected in the options page.

**Comment by yanivtal** [comment]
Cool thanks. I tried turning off the serialization setting but my app till crashed. Thanks for looking into it. I really love using this!

**Comment by zalmoxisus** [comment]
Yes, in your case, you need the serialization to be turned on. It should be fixed now in 0.4.1. It will be available on Chrome store in few minutes.

Thanks a lot for your feedback! Feel free to reopen the ticket if something goes wrong.

**Comment by yanivtal** [comment]
Awesome it works. Thanks!
