### ISSUE TITLE
A way to open it programmatically?

### ISSUE THREAD

**Issue by erikras** [zalmoxisus/redux-devtools-extension#16]
I'd love to be able to do this:
```js
window.devToolsExtension.open();
```

**Comment by zalmoxisus** [comment]
Hey, @erikras. You mean open it in a new window? As neither action page (popup) nor Chrome devtools panel is allowed to be opened programmatically.

If yes, it can be easily implemented.

**Comment by erikras** [comment]
Sure, in a window.

**Comment by zalmoxisus** [comment]
OK.

BTW, in case you intend to use the extension with `redux-form`, just a disclaimer. Chrome extensions are not allowed to communicate with web pages directly (it's more about the chrome extensions architecture than a security case). Because of that, we relay all the lifted store changes to the extension background script all the time, and from there the extension can get actual states. If the store is complex enough, it could be a very expensive operation (especially if it serialized). Of course it can be solved adding more delay and limit actions on the options page, but anyway it works slower than just using `Redux DevTools`. If you try it with `redux-form`, let me know whether it copes with such big amount of actions.

**Comment by erikras** [comment]
[Seems pretty good](http://erikras.github.io/redux-form/#/examples/simple).

**Comment by zalmoxisus** [comment]
Great! 

For some reason we lost the context menu there :-/. I'll look into it.

**Comment by zalmoxisus** [comment]
Done in `0.4.2`. Chrome will autoupdate the extension in few hours. To get it now, just remove it and install again from Chrome store.

Also [added your example](https://github.com/zalmoxisus/redux-devtools-extension/commit/249c4252e795b6dc464c073a2099af2caeeaddab).

**Comment by erikras** [comment]
Awesome. I updated my page to let you click to open it.

Thanks!

**Comment by ORESoftware** [comment]
Link is dead
