### ISSUE TITLE
Wrong persistState session id?

### ISSUE THREAD

**Issue by peteruithoven** [zalmoxisus/redux-devtools-extension#18]
When using `...?debug_session=a` for persistant state, the state is stored under the following key in localStorage:
`redux-dev-session-?debug_session=a,a`
This is because the whole String.match() result is used, instead of a specific group, see: 
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/store/configureStore.js#L9-L11
When debug_session is available, the second array item should be used as id.

**Comment by peteruithoven** [comment]
Also see: https://github.com/gaearon/redux-devtools/issues/191

**Comment by zalmoxisus** [comment]
Hey @peteruithoven,

I thought it is the intended result, isn't it?
It's the same as in the docs and the [redux-devtools' example](https://github.com/gaearon/redux-devtools/blob/next/examples/counter/src/store/configureStore.dev.js#L11-L13) get the same key. I do not see as well why we double the id, but it is better to discuss it on the [redux-devtools repo](https://github.com/gaearon/redux-devtools) or maybe @gaeron could answer it here.

**Comment by peteruithoven** [comment]
We don't double it, `String.match()` just returns an array in which the first item is the whole match and in this case the second is the actual session id. I also opened an issue in the redux-devtools repo.

**Comment by zalmoxisus** [comment]
Got it. I saw your solution. If you make a pull request here, I'd merge it.

**Comment by zalmoxisus** [comment]
Thanks, @peteruithoven. I also removed `redux-devtools-dock-monitor`, so now we do not store unnecessary data like position, size and visibility. Probably, we could create a pull request to `redux-devtools-log-monitor` in order to make `monitorState` optional, so we could remove it at all from the stored object.

New version (`0.4.3`) should be updated automatically from Chrome store.

Also, I added a proposal (#20) to extending persistState. If you have some more suggestions, it's better to continue the discussion there.
