### ISSUE TITLE
Not working with redux-form

### ISSUE THREAD

**Issue by BTMPL** [zalmoxisus/redux-devtools-extension#206]
Hello

I'd like to follow up on my previous issue ( https://github.com/zalmoxisus/redux-devtools-extension/issues/198 ) 

I think I've isolated the issue to redux-form. Example of erratic behavior:

1. clone and run https://github.com/erikras/redux-form/tree/master/examples/initializeFromState 
2. press "load account"
3. use redux-devtools Slider to rewind one step
4. use Slider to go forward on step

The state isn't repopulated

No idea what's causing the issue, can anyone confirm?

**Comment by zalmoxisus** [comment]
@BTMPL, thanks for investigating this!

To see what exactly action is applied select Log Monitor instead of Inspector (from the select box on the top).

I just tried [the demo](http://redux-form.com/6.0.2/examples/initializeFromState/) and it works as expected. When you dispatch `redux-form-examples/account/LOAD` action, after a while another action (`redux-form/INITIALIZE`) is dispatched in the background. When you go back to `redux-form-examples/account/LOAD`'s state, `redux-form/INITIALIZE` is dispatched again. So actually the next time you will go back to the second `redux-form/INITIALIZE` instead of `redux-form-examples/account/LOAD`, and that's why the state is the same.

Not sure why `redux-form/INITIALIZE` is dispatched every time we're time travelling, maybe @erikras can give more details.

**Comment by BTMPL** [comment]
@zalmoxisus thanks for pointing out those actions - they were in ignored list in my extension config (not sure if that's by default or not - if those are there by default might consider removing them as it might end up confusing more people :)); removing them from the ignored list allows me to navigate through them all and is repopulating the app state as expected.

Only issue I'm seeing now (with the demo app) is that navigating back-and-forth fires up another redux-form/INITIALIZE action all the time as you've noticed. 

It's not affecting my app anymore but I guess it's not expected. 

Thanks for your help again, think we can close this issue unless it will come handy for @erikras

Thanks again for your help.

**Comment by zalmoxisus** [comment]
> I guess it's not expected.

Agree. We can continue the discussion here as it's related to both projects.

A solution we have for dealing with side effects when time-travelling is to [check `isTimeTraveling` function](https://github.com/zalmoxisus/redux-devtools-extension/releases/tag/v2.3.0) on `redux-form` part. Not sure it is the best way to solve this.

> they were in ignored list in my extension config

That's another problem. We should "jump" blacklisted actions' states.

**Comment by zalmoxisus** [comment]
Now we have the ability to lock changes, so there will be no side effects like this while time travelling. [See the post](https://medium.com/@zalmoxis/improve-your-development-workflow-with-redux-devtools-extension-f0379227ff83) for details on how to get it.
