### ISSUE TITLE
Constantly replaying actions + multiple instances in the dropdown

### ISSUE THREAD

**Issue by okonet** [zalmoxisus/redux-devtools-extension#207]
I'm using a version from Chrome store with Chrome Version 52.0.2743.116 (64-bit) and seeing a very strange behavior:

1. I can't find a tab in the developer's tools. See #95 
1. The extension constantly replaying all my actions
1. It adds multiple instances to the target dropdown

See video:

![2016-09-06 at 22 51](https://cloud.githubusercontent.com/assets/11071/18290617/7d48da24-7484-11e6-8d2b-d1a480a3dda2.gif)

I've followed the setup instructions and installed the extension from Play store.

Here is my code to integrate it:

```js
import { compose, createStore, applyMiddleware } from 'redux'
import thunk from 'redux-thunk'
import reducer from './reducers'

export default function configureStore(initialState) {
  const store = createStore(reducer, initialState, compose(
    applyMiddleware(thunk),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  ))

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('./reducers', () => {
      const nextReducer = require('./reducers').default // eslint-disable-line
      store.replaceReducer(nextReducer)
    })
  }

  return store
}
```

**Comment by zalmoxisus** [comment]
Something goes wrong there for sure.

Can you replicate this problem with [our demos](https://github.com/zalmoxisus/redux-devtools-extension#demo)? If not a minimal repo to reproduce that would help.

**Comment by okonet** [comment]
I could not reproduce it with the demos (remote or local). I also checked demos against my repository and they look almost identical. My repository is located here: https://github.com/okonet/fifteens-trix.

**Comment by zalmoxisus** [comment]
Thanks for the example. BTW, great app!

Unfortunately, I cannot replicate it there, it works without problems. Was thinking it could be related to hot-reloading, but cannot replicate with it either.

I'm working now on refactoring everything so it should be possible to detect such bugs easier (by [debugging Redux DevTools Extension with Redux DevTools Extension](https://twitter.com/mdiordiev/status/773429801969389569)).

However, it's strange that you don't have the `Redux` tab. That issue you were pointing was because of using an old version of Chrome.

**Comment by okonet** [comment]
Hmm, weird. I've tried re-installing all `node_modules` as well but still can reproduce it locally. Any idea where to look for the source of this?

**Comment by zalmoxisus** [comment]
Open `chrome://extensions/`, on the top of the page check `Developer mode`, then find the extension and click on `Inspect views: background page`. Maybe there's an error you can see in the console there. I guess removing and installing the extension again should solve the problem, though we'll not know what was the bug.

BTW, I'm using exactly the same version of Chrome `Version 52.0.2743.116 (64-bit)`.

**Comment by okonet** [comment]
Re-installing the extension solved it! Thanks so much for your assistance @zalmoxisus!

**Comment by zalmoxisus** [comment]
Well, I did some investigations. 

When starting webpack then stopping (killing) it, HMR is making requests like `http://localhost:3000/sockjs-node/603/an1v2ad3/xhr_streaming?t=1476785078968` till gets a response. So, when you start webpack again, there will be a response like `{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":2710110471}` and everything will continue to work just fine.

However, if you stop that webpack session and still keep that browser's tab opened, and start it for another app on the same port but without `webpack-dev-server`, that url above will return the app itself instead of a json response. For some weird reason Webpack's HMR (or sockjs) includes that wrong response in iframes. So, it creates and removes iframes with your app infinitely. Since the extension sends data from every instance of your app, it gets flooded as in the screenshot above.

I guess it's related to #226 as well.

The most appropriate solution I figure is to add a delay for the extension's initialization, so those phantom iframes would have no effect, as they would be destroyed before the extension is initiated.
