### ISSUE TITLE
MacOS when chrome in full screen/maximized and refresh it opens redux-tools in another desktop

### ISSUE THREAD

**Issue by hackhat** [zalmoxisus/redux-devtools-extension#229]
I can't work with redux dev tools and chrome on full screen because it opens the redux dev tools window in another desktop and moves me to the other desktop. It's so annoying that I have to uninstall the redux tools every time I finish any redux work. And install it again before any work.

I have to work with chrome in a window and the dev tool in another window and is really bad. I have it on windows too, and it works perfectly in it's own dev tab instead of a new window.

**Comment by zalmoxisus** [comment]
Thanks for the report. Yes, I was experiencing this as well during one of my talks. However, instead of uninstalling the extension, you could just close the extension's window (Cmd + W). Also, you can use the extension in the same window, opening it from Chrome devpanel:
![image](https://cloud.githubusercontent.com/assets/7957859/19434758/fd9ae3c4-946f-11e6-9b38-c685be6f37c2.png)

If you think we can do more from our side, let me know.

**Comment by zalmoxisus** [comment]
I misunderstood the issue. The extension doesn't auto-open its windows. Just remove `window.devToolsExtension.open` from your code and open it explecitely.

**Comment by hackhat** [comment]
@zalmoxisus that's great! Sorry I didn't knew that this codebase had that line `window.devToolsExtension.open()`. Thanks it solved the issue

**Comment by zalmoxisus** [comment]
No problems. People often have this issue with auto opening windows. Could you please point me to the boilerplate or part of the docs is responsible for that?
