### ISSUE TITLE
Angular 1 $apply()

### ISSUE THREAD

**Issue by Darkbladecr** [zalmoxisus/redux-devtools-extension#250]
Great work with this extension, I have been using the original redux-devtools for some time and would like to migrate to this extension, but I have some issues with updating my view correctly.

Previously I was able to gather all actions from the `DockMonitor` directly and update the view accordingly:
```
const run = ($ngRedux, $rootScope) => {
  'ngInject';

  const componentDidUpdate = DockMonitor.prototype.componentDidUpdate;
  DockMonitor.prototype.componentDidUpdate = function() {
    $rootScope.$evalAsync();
    if (componentDidUpdate) {
      return componentDidUpdate.apply(this, arguments);
    }
  };

  ReactDOM.render(
    <DevTools store={$ngRedux}/>,
    document.getElementById('devTools')
  );
};
```

However now I have a slight issue with connecting to the extension. I am using the `.subscribe()` method to track actions carried out by the monitor, but I am only logging the initial 'START' action. What am I doing wrong here?

```
const run = ($rootScope) => {
	'ngInject';
	'use strict';
	const withDevTools = (
		// process.env.NODE_ENV === 'development' &&
		typeof window !== 'undefined' && window.devToolsExtension
	);
	if (withDevTools) {
        $rootScope.$evalAsync();
		const devTools = window.__REDUX_DEVTOOLS_EXTENSION__.connect();
		devTools.subscribe((message) => {
			if (message) {
				console.log(message);
                $rootScope.$apply();
			}
		});
	}
};
```
You can see here that toggling the actions does not actually get called onto the console:
![screen shot 2016-11-05 at 15 45 43](https://cloud.githubusercontent.com/assets/4283896/20031420/035744d4-a36f-11e6-9e5f-f63337d813ab.png)
![screen shot 2016-11-05 at 15 45 59](https://cloud.githubusercontent.com/assets/4283896/20031421/06fe12fc-a36f-11e6-8555-24ef5b24e4a2.png)

**Comment by Darkbladecr** [comment]
If you would like to clone and try. You can use the eggly-redux repository, which mimics my redux setup.
https://github.com/simpulton/eggly-redux

**Comment by zalmoxisus** [comment]
@Darkbladecr, it's not quite clear what you want to accomplish here.

[Redux DevTools](https://github.com/gaearon/redux-devtools) and the extension are different projects and you shouldn't mix them. So, no need to include monitors in your app as they are just React components.

I don't know what `$ngReduxProvider.createStoreWith` stands for, but the extension's enhancer should goes here.

`window.__REDUX_DEVTOOLS_EXTENSION__.connect` is for sending actions directly to the extension (while `subscribe` is to get data from the extension). So, you're not getting anything there because you didn't send anything. However, if you already have a Redux architecture, better to apply the store enhancer. If not use one of the approaches described [here](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f).

**Comment by Darkbladecr** [comment]
Sorry I didn't make myself clear. The 1st code block is my previous setup with [Redux-devtools](https://github.com/gaearon/redux-devtools). I am now trying to migrate to this great extension. So I have removed all the dependencies to react etc... and am now loading the `window.__REDUX_DEVTOOLS_EXTENSION__` as an enhancer.

The `$ngReduxProvider.createStoreWith()` is simply a wrapper for `redux.createStore()`, so I am passing the enhancer here. 

So if I understood the API correctly `subscribe` should be able to relay all the actions the extension delivers (JUMP_TO_STATE, DISPATCH etc). This way I can tell my UI to update when an action is delivered from extension instead of waiting for angular's next digest cycle?

**Comment by Darkbladecr** [comment]
I have managed to get it to work with a bit of a hack:
`$ngRedux` is my redux store.
```
if (withDevTools) {
	$rootScope.$evalAsync();
	$ngRedux.subscribe(_ => {
		setTimeout($rootScope.$apply.bind($rootScope), 100);
	});
}
```

**Comment by zalmoxisus** [comment]
> So if I understood the API correctly subscribe should be able to relay all the actions the extension delivers (JUMP_TO_STATE, DISPATCH etc). This way I can tell my UI to update when an action is delivered from extension instead of waiting for angular's next digest cycle?

Yes, but the problem is that `connect` estabilish a new connection (instance) you can see it clicking on that select with `Autoselect instances`. So, it is independent form the instance coming from the enhancer.

You could try to provide an `instanceId` parameter  with the same value to both the enhancer and connect, but not sure how it will work.

**Comment by zalmoxisus** [comment]
@Darkbladecr are you still experiencing any troubles with this? Should we add to the API a way to hook into already connected instances to deal with such cases?

**Comment by Darkbladecr** [comment]
I don't have any trouble as the above example works for me, we can close this.
