### ISSUE TITLE
[Suggestion] Always show both slider arrow buttons

### ISSUE THREAD

**Issue by pmulac** [zalmoxisus/redux-devtools-extension#254]
The slider has two arrow buttons that are used to move forward and backward through state history ( `<` and `>`).  When the slider is at either end of the history stack, one of the arrows becomes hidden.  For example, when the slider is at the most recent state snapshot, the "forward" button is hidden.

This is frustrating because when I use the slider, my eyes are focused on the web application, not the buttons.  When I click the arrow button, the other arrow button appears, which causes the buttons to shift positions.  And when that happens, I end up clicking the wrong button or the slider itself as I navigate through the history.

I would suggest that both arrow buttons be visible at all times, and if the cursor is at either end of the slider, the corresponding arrow button be disabled/greyed-out, rather than hidden.  This way, your eyes can focus on the changes of the web application (not the position of the arrow buttons) as you navigate history.  I think this would improve the experience of time-travel debugging.

**Comment by zalmoxisus** [comment]
Thanks for the suggestion. Yes, I wanted to save some space, but noticed that annoying behaviour as well. I'll look into it later.

In case you have some time to contribute, [the slider component is in a separate lib](https://github.com/zalmoxisus/remotedev-slider), and have also [an example you can run](https://github.com/zalmoxisus/remotedev-slider/tree/master/examples/todomvc).

Basically, you can just [add `disable` prop instead of removing the buttons](https://github.com/zalmoxisus/remotedev-slider/blob/master/src/Slider.js#L215). Then we could add a global style in the extension like:
```
button:disabled: { opacity: 0.5; cursor: initial; }
```

**Comment by zalmoxisus** [comment]
Implemented in the latest. Thanks for the suggestion!
