### ISSUE TITLE
Notify if there are any javascript errors on the page

### ISSUE THREAD

**Issue by deathmood** [zalmoxisus/redux-devtools-extension#27]
When enabled both redux-devtools chrome extension and [javascript error notifier](https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd?hl=en) or [this error notifier](https://chrome.google.com/webstore/detail/javascript-error-notifier/fkkmnicjnabnlplcamfdbbjkcbgdjffm?hl=en)  - notifiers just do not work. 

Can it be that redux-devtools somehow block them?

BTW I've tried one [more extension](https://chrome.google.com/webstore/detail/jnote-javascript-error-no/lbanfockeolepbplfjpgfbnnemkdcdhg?hl=en) and somehow it works.

**Comment by zalmoxisus** [comment]
Doesn't that work only for the app that includes devtools or for all sites?

**Comment by deathmood** [comment]
I've tested it on localhost. If I run app that does not use redux [javascript error notifier](https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd?hl=en) works and shows errors - even if redux extension is enabled.

But if I run app that uses redux -   javascript error notifier does not work

**Comment by zalmoxisus** [comment]
I see, then the problem is related not to our extension itself, but to the fact that Redux DevTools [capture errors](https://github.com/gaearon/redux-devtools/blob/0a1458cdbd50ea2a345fb8d913f7e0d1c763f42b/src/devTools.js#L44).

We may add the ability to disable it on the options page, but don't think it would be so essential as showing errors directly in DevTools is one of the core feature.

Maybe better to add the functionality of that extension to ours? So when an error occurs, we get a notification, which could open DevTools window onclick (showing errors there is already implemented).

**Comment by deathmood** [comment]
Actually it would be very nice to have error notifying in devtools - at least something like "red counter" on top of redux extension icon that shows number of errors. Pop up notifications would be even better.

**Comment by deathmood** [comment]
I mean smth like this 
![image](https://cloud.githubusercontent.com/assets/2758540/11746224/9d34c76e-a025-11e5-9cdd-463c7f299494.png)

**Comment by zalmoxisus** [comment]
Implemented in `v0.4.8`. It is not possible to add badges ("red counter") to the page action (only for the browser action), nevertheless we'll not have more than one error there. So, we show a notification and make the icon red when an error occurs.

**Comment by deathmood** [comment]
updated to 0.4.8 - but it does not seem to work for me(((  At least reference errors are not caught. What kind of errors should be displayed?

![image](https://cloud.githubusercontent.com/assets/2758540/11844906/e60f093e-a419-11e5-8d8f-07bd2871e6e5.png)

**Comment by zalmoxisus** [comment]
I see. I didn't look in depth, it seems that Redux DevTools catch only the errors in reducers.

BTW, just checked [javascript error notifier](https://chrome.google.com/webstore/detail/javascript-errors-notifie/jafmfknfnkoekkdocjiaipcnmkklaajd?hl=en), you referred to, it catches other errors than those from reducers. They should fit well together. The problem is only with the source map loosing the stack, which is an webpack / browser issue.

Actually, it's easy to copy the functionality of those extensions, it's just:
```js
window.addEventListener('error', function(e) {
  // Notify
});
```
The problem is only how to display them as it is not related to Redux DevTools' tree.

**Comment by zalmoxisus** [comment]
Implemented in `v.0.4.9`. Should notify on non-reducer errors as well.

**Comment by deathmood** [comment]
thanks much! works now

**Comment by zalmoxisus** [comment]
You're welcome. Thanks to you for the suggestion!
