### ISSUE TITLE
crashes about once a day

### ISSUE THREAD

**Issue by davidjnelson** [zalmoxisus/redux-devtools-extension#29]
I absolutely love your extension, it is amazing.  I rated it 5 stars.  Thanks so much for making it!

I don't know much about chrome plugin development.  How can I give you a helpful bug report?

What happens is I'll be using it fine, then about once a day the chrome developer tools window I have docked next to the extension will shrink to the window size I had the extension running at, and the extension window will close.

When this happens the icon in the main chrome window's address bar is no longer present.  Sometimes reloading the page fixes it, sometimes disabling and re-enabling the extension then reloading fixes it.

I am using the extension docked to the right of my application window.

Let me know how I can provide more useful info, thanks!

**Comment by zalmoxisus** [comment]
Hey @davidjnelson,

Thanks for report this. It's probably related to #23. I added [a test which simulate a high activity](http://zalmoxisus.github.io/redux-devtools-extension/examples/router/). Select AutoTodo and check if it will crash the extension.

Also please try using the extension's window (open from the context menu or [using shortcuts](https://github.com/zalmoxisus/redux-devtools-extension#keyboard-shortcuts)) instead of chrome developer tools, as the latter cannot use the store variable directly and we have to relay it, which is less performant.

**Comment by zalmoxisus** [comment]
Should be fixed in `v0.4.12`. Feel free to reopen the issue if it still happen.

**Comment by varun-dev** [comment]
Hi,

In my team, the chrome devtools window keeps crashing upto 50% of the time. But your suggestion to use context menu option works, I never used that assuming it will open the same.

**Comment by zalmoxisus** [comment]
@varun-dev I suspect the extension is using too much RAM and Chrome is terminating it. Could you please check if RAM consumption is increasing significantly?

Extension's windows are running on the same process as the extension's background page, while devpanel is in another process. Because of that we have the data duplicated, so in that case we're using two times more RAM.

I've been checking for memory leaks recently. However, the monitored state can be huge.
