### ISSUE TITLE
import Symbol issue.

### ISSUE THREAD

**Issue by 375683067** [zalmoxisus/redux-devtools-extension#302]
After your update for some reason Symbol that I'm importing from action constants to reducer is not equal to Symbol that I import to action from same constant file.
I've spent a lot of time to figure out why my reducers doesn't works.

Action constant:
`export const SOME_ACTION_SYMBOL = Symbol('SOME_ACTION_SYMBOL');`
Action:
```
import * as actions from '../constants/actions';
export function myAction (limits) {
  return {
    type: actions. SOME_ACTION_SYMBOL,
    usefullData
  };
}
```

Reducer:
```
import {SOME_ACTION_SYMBOL} from '../constants/actions';
let defaultState = {};
/**
 * @param {object} action - {usefullData: nevermind, type: Symbol}
 */
export function MyReducer (state = defaultState, action) {
  switch (action.type) {
    case SOME_ACTION_SYMBOL:
     //code is never gets to this place
      state = action.usefullData;
      break;
  }
  return state;
}
```

**Comment by zalmoxisus** [comment]
Sorry about that. I was relying on `Symbol.for`, and forgot that others use the constructor as well.

I wanted to add support for symbols out of the box, so you'd be able to inspect data and even export / import. Before you'll just get an empty action type in the monitor.

It would work if you use `Symbol.for` because `Symbol.for('SOME_ACTION_SYMBOL') === Symbol.for('SOME_ACTION_SYMBOL')`, but `Symbol('SOME_ACTION_SYMBOL') !== Symbol('SOME_ACTION_SYMBOL')`.

 I've reverted that change in `2.13.0.3`, it will be available in maximum an hour on [Chrome Store](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd).

**Comment by 375683067** [comment]
Seems that everything is ok for now. Thank for your efforts..

**Comment by zalmoxisus** [comment]
Thanks for letting me know.

To get better support for symbols, [set `serialize` parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Troubleshooting.md#symbols-or-other-unserializable-data-not-shown).
