### ISSUE TITLE
Blacklisted actions still contribute to the actions history

### ISSUE THREAD

**Issue by apendua** [zalmoxisus/redux-devtools-extension#316]
I would like to hide some type of actions in Redux DevTools history. In the documentation I've found an information about `actionsBlacklist` option, which I am passing to

    window.__REDUX_DEVTOOLS_EXTENSION__(...)

This has some effect, i.e. I no longer see the blacklisted actions, but behind the scenes they still contribute to the history length, so instead of seeing the history of default length (50) I can only see a couple of most recent actions that has not yet been pushed back but the blacklisted ones.

Looks like increasing the history length, which as far as I understand is controlled by the `maxAge` option, helps a bit but it feels like a workaround rather than a real solution.

I am wondering if there's a better way to fix this behavior which I described above and if it's even intended or just a BUG?

**Comment by zalmoxisus** [comment]
I know this is confusing, we should add more details about it in the docs. The intention is indeed to only hide those action on the monitor part. So they are only not being sent to the extension, but still are present in the lifted state history on the client side. Skipping those actions at all would lead to an inconsistent state during hot reloading and other devtools actions (which invokes recomputing teh reducers with all the action objects from the history). In other words, [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument) stores those actions, but the extension not. Since `maxAge` is applied to `redux-devtools-instrument`, it affects the "real" history length, not the actions showed in the extension monitors. It's good to keep this parameter as is, because it determines how much RAM will be consumed on the client side (not the extension part).

If you have any ideas on how to describe this better in the docs, a PR would be much appreciated.

**Comment by apendua** [comment]
@zalmoxisus Thanks! Looks like it's a difficult case to solve then.

**Comment by funwithtriangles** [comment]
This is affecting my project too. My app has some actions that are firing multiple times a second. I have blacklisted these, but because of the limit imposed with `maxAge`, it is making all other actions in the log invisible.

The solution I have for now is to increase `maxAge` and `latency`. Unfortunately this means that the actions I want to see appear in the log for a few seconds and then disappear!

**Comment by hackhat** [comment]
Any solution for this?

**Comment by Venryx** [comment]
I have the same issue. Looks like I'll have to remove some frequently-firing actions from the redux store and instead use an alternate system, as this issue currently makes inspecting the other actions impossible.

**Comment by zalmoxisus** [comment]
It's implemented in `2.16`, which will land in a day on Chrome Store. It works only for balcklisted/whitelisted actions. For `predicate` it would require a major refactoring as the state is computed after maxAge is called.

**Comment by Venryx** [comment]
Thanks for the addition. I'll try it out at some point, when I'm back on the project I had the issue in.
