### ISSUE TITLE
Infinity values shown as null

### ISSUE THREAD

**Issue by Seaviello** [zalmoxisus/redux-devtools-extension#332]
All tabs (action, state, diff, test in modes: tree, chart, raw) show Infinity (plus and minus) as null value.

I was looking for a bug in my reducer, but everything was correct. Simple test with action dispatcher with Infinity shows, that problem is not in my code (screens).
![1](https://cloud.githubusercontent.com/assets/12865454/24815194/a9baacac-1bd4-11e7-8039-965761a73993.PNG)
![2](https://cloud.githubusercontent.com/assets/12865454/24815195/a9bfcfca-1bd4-11e7-8145-99cb34bc939f.PNG)

**Comment by zalmoxisus** [comment]
That's because `JSON.stringify` converts `Infinity` to `null`. Currently we add [custom serialization](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#serialize) of date, regex, undefined, error objects, symbols, maps, sets and functions via [`jsan`](https://github.com/kolodny/jsan). A PR there to also support `Infinity`, `-Infinity` and `NaN` would be much appreciated.

**Comment by Seaviello** [comment]
Thank you for the answer. I really didn't know, that these values are not serializable to JSON.

**Comment by zalmoxisus** [comment]
It works in `2.15.0`. Thanks to @davidfurlong for implementing this.

**Comment by VinceSJ** [comment]
I think this should be re-opened. I'm currently using 2.15.1 on up-to-date Chrome.  `NaN` is displaying as `null`. I'm testing by directly setting the initial state of a field as `NaN`, but the Redux dev tools display that field as `null`. Let me know if you need more info.

**Comment by VinceSJ** [comment]
@zalmoxisus Has anyone looked into reopening this issue? I'm still seeing the same behavior I commented above. Just ran into it again when I was confused why a numerical value was being set to `null` after a math operation. Logged it in console, saw it was actually coming out as `NaN`.

**Comment by jakewisse** [comment]
Seeing this in 2.15.3 as well.

**Comment by VinceSJ** [comment]
Pinging @zalmoxisus -- sorry to notify you if you're already aware of this issue, but was worried you might not have seen any of the activity since the issue is closed. It looks like the fix for undefined, NaN, Infinity and -Infinity from 2.15.0 hasn't held up for some reason. Many thanks if you have the chance to look into it.

**Comment by RobertShaw1** [comment]
@zalmoxisus, I think there may have been another regression.  I just came across this issue with NaN values again on v2.17.0.

**Comment by msalafia** [comment]
Hi from 2023! Still getting `null` for an `Infinity` value.
