### ISSUE TITLE
Scroll Window to the bottom

### ISSUE THREAD

**Issue by dexwiz** [zalmoxisus/redux-devtools-extension#34]
Whenever I open up the action list, either in the pop up in the url bar, or in my dev tools tray, it defaults to showing the first action. When I open it, usually I am interested in the latest action, not the first. Can I get an option to auto scroll to the bottom?

**Comment by zalmoxisus** [comment]
Good point! The default monitor for Redux DevTools was expected to be empty when it is mounted, that's why it invokes scrolling on [`componentDidUpdate`](https://github.com/gaearon/redux-devtools-log-monitor/blob/acd48a7d18e54775ed03b4c21166aa6a0df0c44b/src/LogMonitor.js#L124). In our case we need it also on `componentDidMount`. As we plan to support other monitors, I will look how they deal with this, so then I'd be able to decide whether to add a pull request to [redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor) or to implement the autoscrolling here.

**Comment by zalmoxisus** [comment]
Should work in `v1.0.0-beta3`, but I'll keep the issue open till we have it merged in [`redux-devtools-log-monitor`](https://github.com/gaearon/redux-devtools-log-monitor/pull/32).

**Comment by gaearon** [comment]
Log Monitor 1.0.4 includes this.
