### ISSUE TITLE
redux devtools INIT action

### ISSUE THREAD

**Issue by kevinluvian** [zalmoxisus/redux-devtools-extension#351]
I noticed that redux devtools has unique init action which is "@@INIT", i am not sure why, but it breaks my app by resetting the state if i have action between @@INIT and @@redux/INIT.
I can walk around the first @@INIT by using setTimeout to delay my action to be after @@redux/INIT. then the app run well, however, after changing the location (using react router redux), the init got called again and reset my state

this problem didn't appear few days ago, and I have not changed my code, so it must be something wrong here, because when I remove redux dev tools, everything went perfect

**Comment by zalmoxisus** [comment]
This is caused by https://github.com/zalmoxisus/redux-devtools-instrument/commit/5a69ccedc3429ab688f91403e9071ad3e01d329b, which aims to solve #326. Currently there 2 scenarios when `replaceReducer` is invoked:
1. Recompute the action history, which is by default.
2. Reset the state to apply the new reducer state, which works when `shouldHotReload` is set to `false` (see [the tests](https://github.com/zalmoxisus/redux-devtools-instrument/commit/5a69ccedc3429ab688f91403e9071ad3e01d329b#diff-c45c15dd526587bbe760a417b9de6304)).

Before [we did nothing](https://github.com/zalmoxisus/redux-devtools-instrument/commit/5a69ccedc3429ab688f91403e9071ad3e01d329b#diff-9dd65be703999bb051f530e79908a0c9L510) in the second case, which is what you expect, but when the new applied reducer change the state structure (which usually is what we intent to do by replacing the root reducer) it will wrongly return the obsolete state.

I'm open for the suggestions on how to handle `replaceReducer` better.

**Comment by kevinluvian** [comment]
can we have a new config like shouldHotReloadAndReset for that?

**Comment by zalmoxisus** [comment]
The problem is that the previous handling of `shouldHotReload` wasn't working correctly to restore it. It was returning the previous state not the current one.

Could you please provide more details about your app? The action lost between `@@INIT` and `@@redux/INIT` is dispatched before replacing the reducer or after?

**Comment by kevinluvian** [comment]
what happen is, i am using replaceReducer for code splitting, and my app only inject a particular reducer when you enter a particular route. and I have an initial reducer for session.

however, with your update, it seems every time my app move to some route, and inject a new reducer, the store get resetted to its initial state (which includes the session state to be nulled)

actually.. I forgot why I use shouldHotReload to be false, but I think it is pretty important..

**Comment by kevinluvian** [comment]
this is the test file, please try it, i use the instrument.spec.js for reference

```
import expect, { spyOn } from 'expect';
import { createStore, compose, combineReducers } from 'redux';
import instrument from '../src/instrument';

import 'rxjs/add/observable/from';

function counter(state = 0, action) {
  switch (action.type) {
    case 'INCREMENT': return state + 1;
    case 'DECREMENT': return state - 1;
    default: return state;
  }
}

function counterWithBug(state = 0, action) {
  switch (action.type) {
    case 'INCREMENT': return state + 1;
    case 'DECREMENT': return mistake - 1; // eslint-disable-line no-undef
    case 'SET_UNDEFINED': return undefined;
    default: return state;
  }
}

function sessionReducer(state = 'no token', action) {
  switch (action.type) {
    case 'SET_SESSION': return action.token;
    default: return state;
  }
}

const makeRootReducer = (asyncReducers) => {
  return combineReducers({
      session: sessionReducer,
      counter: counter,
      ...asyncReducers
    })
}

const injectReducer = (store, { key, reducer }) => {
  if (Object.hasOwnProperty.call(store.asyncReducers, key)) return

  store.asyncReducers[key] = reducer
  store.replaceReducer(makeRootReducer(store.asyncReducers))
}

describe('instrument', () => {
  it('should work', () => {
    let store = createStore(
      makeRootReducer(),
      {},
      instrument(undefined, { shouldHotReload: false })
    )
    store.asyncReducers = {}

    expect(store.getState().session).toEqual('no token')
    store.dispatch({ type: 'SET_SESSION', token: 'new token' })
    expect(store.getState().session).toEqual('new token')
    injectReducer(store, { key: 'counterWithBug', counterWithBug })
    expect(store.getState().session).toEqual('new token')
  })
});

```

**Comment by zalmoxisus** [comment]
I think using the last state instead of [`preloadedState`](http://redux.js.org/docs/api/createStore.html) when reseting would solve the issue. I'll look into it tomorrow, and if it doesn't break anything will publish a patch.

Thanks for the detailed example!

**Comment by kevinluvian** [comment]
sure, thanks!

**Comment by zalmoxisus** [comment]
Hey @kevinluvian, have just published `2.15.1` which should fix according to https://github.com/zalmoxisus/redux-devtools-instrument/commit/0aa43f1aee8847ead13001aec5b5d54ce01c7e12. It should be available in an hour.

If you're still experiencing any troubles, let me know and if possible modify [the tests](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/test/instrument.spec.js#L265-L280).

**Comment by kevinluvian** [comment]
thanks, it worked correctly now

**Comment by vaibhavhrt** [comment]
I was still having some problems, I was setting my initial state to what used to be few days back. Clearing localstorage fixed it.
