### ISSUE TITLE
 react-native's webview postmessage is blocked by redux-devtools-extension

### ISSUE THREAD

**Issue by yinghuaheal** [zalmoxisus/redux-devtools-extension#383]
In react-native, messages between rn and webpage is using 'postMessage' and the message itself is a string. I am using react-native-debugger which is integrated with redux-devtools-extension.

When a message is posted, there will be confusion between redux-devtools-extension and rn code. App stops to run. I think this is because redux-devtools-extension's message is base on a JSON data, while message in react-native can only be a string.

**Comment by jhen0409** [comment]
Do you meaning [react-native-debugger](https://github.com/jhen0409/react-native-debugger)? If yes please file an issue for that, because the logic is implemented in [that repo](https://github.com/jhen0409/react-native-debugger/blob/master/app/worker/reduxAPI.js), it just made the same API with this browser extension.

Also, I guess you do mistake something because that just used the same `postMessage` with [RN official debugger](https://github.com/facebook/react-native/blob/master/local-cli/server/util/debuggerWorker.js#L59).

**Comment by yinghuaheal** [comment]
My app became extremely slow after I clicked a button to postMessage from webpage to react-native. Without redux-devtools-extension ( comment out window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__), everything works just fine. 
I give a check, redux-devtools-extension shows  correct action dispatch and state change process even it takes a long time. You could be right it is a react-native-debugger's issue.

**Comment by jhen0409** [comment]
> My app became extremely slow after I clicked a button to postMessage from webpage to react-native. Without redux-devtools-extension ( comment out window.REDUX_DEVTOOLS_EXTENSION_COMPOSE), everything works just fine.

I can't figure out the problem because the `window.postMessage` from WebView and  `window.postMessage` from debugger worker isn't the same.

> I give a check, redux-devtools-extension shows correct action dispatch and state change process even it takes a long time.

The cause of slow for redux API usually user send large data between app and devtools (action or state), you may need to use [sanitizer](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#actionsanitizer--statesanitizer) options.

**Comment by zalmoxisus** [comment]
Both `react-native-debugger` and browser extension use the same `window.REDUX_DEVTOOLS_EXTENSION_COMPOSE` for convenience, but that doesn't mean you are using Redux Extension. Browser extension has no access to your React Native app and is not applied there.

As @jhen0409 suggested, better to discuss it on [`react-native-debugger`](https://github.com/jhen0409/react-native-debugger) repo a not being related to this one, though the `sanitize` option should help.

**Comment by yinghuaheal** [comment]
@jhen0409 
I send very short data. My 'slow' means whole app is getting slow just after i click to send 'message', not only devtools becomes slow, every screen, touch or animation in my app become slow.  I don't know if you can get what I mean.
