### ISSUE TITLE
Actions Sometimes Leak Between Chrome Tabs

### ISSUE THREAD

**Issue by jongunter** [zalmoxisus/redux-devtools-extension#444]
Steps to reproduce:

1. Open a tab (Tab A) in a Redux SPA. Trigger some actions.
2. Open Chrome DevTools and open the "Redux" tab
3. Open another tab (Tab B) to the same Redux SPA. Trigger some actions.
4. You'll see actions from Tab A **and** Tab B in Tab A's Chrome Devtools Redux tab. It would seem to me that you should only see actions from Tab A.

This only seems to happen in the "Redux" tab of the DevTools window, and only sometimes.
Chrome Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by jongunter** [comment]
I've also noticed this occurs even if Tab B is opened in Incognito mode. (I do a lot of testing where I'll log in as a second user in an Incognito window and make sure my apps work).

**Comment by medmans** [comment]
i have maybe the same issue, i'm using Chrome DevTools, my customer noticed that some data di not appear in the web page before he click anywhere in the page, i have noticed that this scenario fired when the extension is not installed in the brower, i'm stuck for 2 days trying to resolve this issue but no way !

i did not understand what is happening !

**Comment by zalmoxisus** [comment]
If "this scenario fired when the extension is not installed in the browser", the issue is 100% outside of the extension.

As per the other message, not sure if it's a bug, you should have 2 instances with the same name (which can be set [using corresponding parameter](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Arguments.md#name)), if you select one from the dropdown above, only actions for that instance will be displayed. By default the extension doesn't have access to Incognito, unless it was allowed on `chrome://extensions`.

Feel free to reopen the issue with more details if it's still relevant.
