### ISSUE TITLE
No method for creating two sets of options

### ISSUE THREAD

**Issue by Sawtaytoes** [zalmoxisus/redux-devtools-extension#451]
I'd like a way to both blacklist and whitelist the same actions in two separate instances of the same store.

Currently, Redux DevTools extension only allows loading once which makes debugging any blacklisted actions impossible. What would be preferred is creating one instance without blacklisted actions and another whitelisting those same actions.

This would provide more insight in the actions firing state changes whilst optionally hiding chatty ones from view.

**Comment by zalmoxisus** [comment]
The main purpose for blacklisting is to avoid performance issues, though I like the suggestion. A workaround would be to open the app in 2 tabs, with blacklisted and whitelisted actions. So there will be 2 instances in the extension.

**Comment by Sawtaytoes** [comment]
Would it be possible to add the middleware twice and pass the whitelist values in one and the blacklist values in the other?

**Comment by zalmoxisus** [comment]
We're [not allowed that from instrumentation part](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js#L676), because that would dispatch every app action twice in case we'd have many liftedStores. However if you don't need all the futures, only to see actions, that could be done via [extension's API](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#returns). Just add different names to the instances in `window.__REDUX_DEVTOOLS_EXTENSION__.connect` and send them via `devTools.send`. You'd need a simple middleware like [here](https://github.com/zalmoxisus/remotedev/blob/master/examples/redux/store/logRemotely.js).

**Comment by zalmoxisus** [comment]
Actually I forgot that we have [a helper for logging inly](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/npm-package/logOnly.js), you can use it like that:
```js
import { createStore, compose } from 'redux';
import { devToolsEnhancer } from 'redux-devtools-extension/logOnly';

const store = createStore(reducer, /* preloadedState, */ compose(
devToolsEnhancer({
  instaceID: 1,
  name: 'Blacklisted',
  actionsBlacklist: '...'
}),
devToolsEnhancer({
  instaceID: 2,
  name: 'Whitelisted',
  actionsWhitelist: '...'
})
));
```
