### ISSUE TITLE
Log monitor does not update when hot reloading a reducer

### ISSUE THREAD

**Issue by c089** [zalmoxisus/redux-devtools-extension#48]
Steps to reproduce:

1. trigger some actions
2. replace a reducer function

Expected: All actions are replayed, putting the app in the right state and replacing the intermediate states in the log.

Actual: All actions are replayed and the app is in the right state, but the log monitor is not updated.

Note that this only happens in the extension, but not when I include LogMonitor in the app myself.

**Comment by zalmoxisus** [comment]
The new actions should be ok, the problem is only with the history which was stored before the hot-reloading happens. A way to update the history is to toggle an action.

I do not know how to catch hot-reloading from the extension as there's no event to bind to.  We'll probably add a function (let's say `window.devToolsExtension.update()`), which can be added in `module.hot.accept('../reducers', () => { ... })` next to `store.replaceReducer`. Also, a button to update the history could be a good alternative.

Other ideas?

**Comment by zalmoxisus** [comment]
I found a way to catch reducers replacement. In `1.0.0.4` the log monitor should be updated on hot reloading.

**Comment by c089** [comment]
Awesome! Works like a charm, thanks for that :sparkling_heart:

**Comment by zalmoxisus** [comment]
Thank you for the report!
