### ISSUE TITLE
Non-Redux state updates are not shown with closed DevTools

### ISSUE THREAD

**Issue by bisubus** [zalmoxisus/redux-devtools-extension#561]
The behavior between `__REDUX_DEVTOOLS_EXTENSION__()` used with Redux store and `__REDUX_DEVTOOLS_EXTENSION__.connect()` used without Redux store is different. The later requires Redux DevTab tab to be active to get all state updates.

Here is slightly modified [demo](https://stackblitz.com/edit/react-r23knz) from repo examples that uses `__REDUX_DEVTOOLS_EXTENSION__.connect()`. When it's loaded in separate browser tab like https://react-r23knz.stackblitz.io/ with no Redux DevTools active at the moment when the app is initialized, DevTools wait for a connection and then show:

>No store found. Make sure to follow the instructions.

But newer state updates are shown in DevTools. And all state changes are shown including `@@INIT` when Redux DevTools tab is already active during app initialization.

Here's a [screencap](https://user-images.githubusercontent.com/2905949/47011242-ba17c700-d141-11e8-9dc3-021b6e16056e.gif) that shows the problem.

While [this Redux demo](https://stackblitz.com/edit/react-fsiqwd) that uses  `__REDUX_DEVTOOLS_EXTENSION__()` doesn't require to have Chrome devtools opened to get state when it's loaded in separate tab like https://react-fsiqwd.stackblitz.io/ . Redux DevTools can be activated later, all state updates are already there.

**Comment by rhyek** [comment]
I'm developing an Electron app using MobX for global state and am using this methodology to monitor changes. I see the same behavior there. Upon running the app, in order to see any events I need to  first focus the redux devtools tab and then reload the window.

**Comment by zalmoxisus** [comment]
That is easier to use, just by sending every action.

Another way is to collect everything on your part and when the extension is opened (you'll get `START` lifted action), send everything collected as a lifted state. To do that, just use `send` having the first argument as `undefined` and for second argument, instead of current application state, use lifted state. To see the structure of lifted state, you can just export it from the extension or look to [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument/blob/master/src/instrument.js). Unfortunately, there's not enough documentations for integrations. For remote part, some was written [here](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md#4-sending-the-action-and-state-to-the-monitor).

If that's not important to have the history, you can just start sending after you get from extension`START` action, and stop sending when it sends `STOP` action.

**Comment by rhyek** [comment]
@zalmoxisus that worked, thanks!
