### ISSUE TITLE
Redux script injected into every website

### ISSUE THREAD

**Issue by TimNN** [zalmoxisus/redux-devtools-extension#61]
When this extension is enabled, a `<script>` tag is injected into **all** webpages, even with "Inject in all pages" disabled and the regex set to a non-sensical one:

<img width="356" alt="screen shot 2016-02-24 at 23 12 53" src="https://cloud.githubusercontent.com/assets/1178249/13303013/20f15e8e-db4d-11e5-985f-163030ccaac1.png">

I also experimentally used an invalid regex (`(?:`), which did not change this behaviour.

**Edit:** Extension version is `1.0.0.6`, Chrome is `Version 48.0.2564.116 (64-bit)` on OS X.

**Comment by zalmoxisus** [comment]
It is intended behaviour, the script is injected but [not executed](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L141). The problem is that we often get options (settings) after the page is loaded as described in #22, so we don't know whether the script should be injected or not and of course don't want to delay loading of every page waiting for settings being loaded.

Probably we should rename this option. Any ideas? cc: @iamakulov

**Comment by TimNN** [comment]
Alright, thanks for the explanation although I can't say I'm comfortable the script being injected into every website I visit, so I'm going to leave this extension disabled for now. Nevertheless, thank you for providing the extension!

My best idea would be to name the option something like "run on all pages" and add a note that "the script is injected in all pages regardless of this option", ideally with a link / tooltip explaining why this is necessary (maybe link to #22).

**Comment by iamakulov** [comment]
> Probably we should rename this option. Any ideas?

Yep, looks like this. Will look into it later.

**Comment by zalmoxisus** [comment]
@TimNN, yes, enable the extension when you use it. If you have another solution, I'd be happy to implement.
