### ISSUE TITLE
Removing the ability to create a Redux store directly from the extension

### ISSUE THREAD

**Issue by zalmoxisus** [zalmoxisus/redux-devtools-extension#613]
It is possible to create a Redux store directly with the extension (without importing Redux in your app) when you need it for debugging only. It's not about the store enhancer or compose helper as it's usually applied. See [the docs](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/CreateStore.md), [the example](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter/components/Counter.js) and [the blog post](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f) for more details. That was introduces for more than 2 years, but doesn't seem anybody using it. Now with React hooks, that example wouldn't make much sense. One can move that inside an integration including redux for development only, like [`reinspect`](https://github.com/troch/reinspect) does.

The suggestion is to remove that part in next major release. I'll add a deprecation waring in the next minor version.

If you're using it, please let me know about your use case.

**Comment by kimamula** [comment]
I am not sure how React hooks are related to this extension.
I am using this extension in my Angular app (of course without Redux) based on your blog post and found it began outputting the deprecation warning recently.
What is the correct way to use this extension without React and Redux?

**Comment by CharlesStover** [comment]
If this is still an issue, I am in the process of adding [ReactN](https://github.com/CharlesStover/reactn)'s global state to Redux DevTools. Since ReactN does not use a Redux store, it is not possible to pass an existing one. Having the DevTools fallback to making one would be beneficial, such that the dependency lies in the extension instead of in my package. It is detrimental to my users to have them include Redux in their bundle just so that one of their developer tools can show them a store.

Without this feature, I am left having to make my own minimalist implementation of a store so as not to include Redux in my bundle. It's been a burden to create, and will continue to be a burden to maintain. This would be alleviated if Redux DevTools made the store on its end.

As is, I'm currently afraid to rely on Redux DevTools creating the store, given this Issue and the comment about its deprecation(?).

**Comment by nik72619c** [comment]
anybody working on this issue ?

**Comment by anukul** [comment]
Hi! This is used in https://github.com/intergalacticspacehighway/use-reducer-thunk

**Comment by Methuselah96** [comment]
Removed in 3.0.
