### ISSUE TITLE
1.0.0.8 broke serialize state setting

### ISSUE THREAD

**Issue by camwest** [zalmoxisus/redux-devtools-extension#67]
See screenshot: 
![screenshot 2016-03-01 07 45 49](https://cloud.githubusercontent.com/assets/22905/13432274/b356c15a-df81-11e5-969a-5425e586c6fd.png)

I still have states serialization selected:
![screenshot 2016-03-01 07 46 44](https://cloud.githubusercontent.com/assets/22905/13432293/c7cd608a-df81-11e5-837a-7a303cc65c27.png)

Since window.devToolsExtension now takes deserializeState as an option, maybe we should add serializeState as an option there too?

**Comment by zalmoxisus** [comment]
Due to changes in #60, the immutable data is broken on serialization. I reverted it and just published `1.0.0.9`, it will be available on Chrome Store in about an hour. Thanks for the report!

I'll keep this issue open till we get a solution.

**Comment by kolodny** [comment]
hmm, can you give me a minimal case that breaks in jsan that I can try to work with? thanks

**Comment by zalmoxisus** [comment]
@kolodny,
```js
import immutable from 'immutable';
import jsan from 'jsan';

jsan.stringify(immutable.List(), null, null, true);
```

Actually the result `{"size":0,"_origin":0,"_capacity":0,"_level":5,"_root":{"$jsan":"u"},"_tail":{"$jsan":"u"},"__ownerID":{"$jsan":"u"},"__hash":{"$jsan":"u"},"__altered":false}}},"error":{"$jsan":"u"}}` is almost the same as we see in console for `console.log(immutable.List())`, and it is still a mystery how `JSON.stringify` serialize it to `[]`.

**Comment by zalmoxisus** [comment]
I see, thanks for the explanation. I guess it wouldn't be so easy for nested data like `immutable.Map({ someList:  immutable.List(), someMap: immutable.Map() })`.

**Comment by kolodny** [comment]
This is pretty doable by offloading `toJSON()` to whatever is being serialized, however you lose the advantage of working with functions and other types. I would advise checking for a `.toJS` method and then using that for `stringify`, something like

```diff
- message.payload = stringify(message.payload, null, null, true);
- if (message.action !== '') message.action = stringify(message.action, null, null, true);

+ var payload = message.payload && message.payload.toJS ? message.payload.toJS() : message.payload;
+ var action = message.action && message.action.toJS ? message.action.toJS() : message.action;
+ message.payload = stringify(message.payload, null, null, true);
+ if (message.action !== '') message.action = stringify(message.action, null, null, true);
```

I'll still patch jsan to properly handle an object with a `toJSON()`, however I still think this solution is better in this instance

**Comment by zalmoxisus** [comment]
It wouldn't be possible to use `. toJS` in this case as usually only a part of the object is Immutable, which comes from reducers. As in https://github.com/kolodny/jsan/issues/4.

**Comment by rhalff** [comment]
I've also started to experience the `root:` properties today, not the weird serialization of the immutable objects though, I'm using [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) maybe that's why.

Anyway, I found a recent change in [react-json-tree](https://github.com/chibicode/react-json-tree) is probably related.
I've tested the 0.5.3 version and version 0.5.6, something changed with it's `keyName` property, see:

https://github.com/chibicode/react-json-tree/commit/f98e5685fe27ceed626bb85065edde839d0bad09

The LogMonitor is using it here:

https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitorEntry.js#L43
https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitorEntryAction.js#L25

If you test the latest version of react-json-tree you'll see the `keyName` is not being set anymore and is set to `root`.

**Comment by zalmoxisus** [comment]
@rhalff, it's related to https://github.com/gaearon/redux-devtools-log-monitor/issues/39. I'll revert this as well. Thanks for the report.

**Comment by kolodny** [comment]
I just pushed `3.1.1` which should fix this, in particualr to use it with immutable you would do the same as this test does https://github.com/kolodny/jsan/blob/master/test/end-to-end.js#L107-L125 lines 119-120 are where the replacer function that you would need is. Let me know if this fixes it for you

**Comment by rhalff** [comment]
.10 works like a charm again, thanks.

**Comment by zalmoxisus** [comment]
@kolodny, thanks for the changes! I like the idea of nested `.toJS`.

Is this processing suppose to be slower than just `jsan.stringify(obj)`? If so, I will let users to choose which type of serialization to use (say "Regular" or "Deep").

**Comment by kolodny** [comment]
yeah this puts it in the same performance class as the other options, as opposed to without where it's ~ 3x faster for most use cases. Putting it behind a flag would make the most sense

**Comment by zalmoxisus** [comment]
Thanks a lot, @kolodny, for all the work and detailed explanation!

I published  `1.0.0.11` reflecting  this changes. Will keep this by default, so more users can test it. When we finish the options page, will add the ability to select between: "No serialization", "Regular serialization", "Deep serialization".

**Comment by amannn** [comment]
@zalmoxisus I tried getting the serialization to work with [seamless-immutable](https://github.com/rtfeldman/seamless-immutable) but I couldn't get it to work.

With the old API this is pretty easy:

```js
import Immutable from 'seamless-immutable';

compose(enhancer, window.devToolsExtension({
  deserializeState: Immutable
}));
```

How would this work with the new API? I've tried:

```js
compose(enhancer, window.devToolsExtension({
  serialize: {reviver: (key, val) => Immutable(val)}
}));
```

But this throws `Cannot assign to read only property 'something' of object '#<Object>'`. `something` in this case is a field name in my redux state. I guess it's trying to do something like `state.something = {…}` instead of `state.merge({something: {…}})` but I don't know how I can specify that.

Could you help me with this? Thank you!

**Comment by zalmoxisus** [comment]
@amannn there are 2 issues here:
1. `reviver` unlike `deserializeState` will be called for every child of the object tree.
2. it will be applied for both state and action.

The solution would be to mark the immutable data structure when serialized like [we do for ImmutableJS](https://github.com/zalmoxisus/remotedev-serialize/blob/master/immutable/serialize.js). It would allow to use such structure not just for root state, but for some reducers only. Also it would support such structure in actions payloads.

Roughly `serialize` should be:
```js
{
  replacer: (key, value) => (
    typeof value === 'object' && value !== null && Immutable.isImmutable(value) ?
      { data: Immutable.asMutable(value), __serializedType__: 'Immutable' } : value
  ),
  reviver: (key, value) => (
    typeof value === 'object' && value !== null && value.__serializedType__ === 'Immutable' ?
      Immutable(value) : value
  )
}
```

As a bonus you'll see in the Inspector Monitor which data is immutable.

We could include it in [the seialize lib](https://github.com/zalmoxisus/remotedev-serialize) to have it out of box if it works well.

**Comment by amannn** [comment]
@zalmoxisus Thanks for the quick reply!

I still got some errors every now and then, which I couldn't really isolate to find the root cause.

I went with putting `state = ensureImmutable(state);` at the top of every reducer, where `ensureImmutable` is `state => Immutable.isImmutable(state) ? state : Immutable(state);`. This is not too bad for my app as I don't have so many reducers. Also I'm planning on using the replay feature independently of the redux-devtools-extension by importing user sessions for analytics purposes – I think it will be beneficial for that use case if I don't have to mark parts of the state with `__serializedType__` when saving user sessions.

Thank you very much though!

**Comment by zalmoxisus** [comment]
@amannn you can use that workaround only when `window.__REDUX_DEVTOOLS_EXTENSION__` is defined not to affect the performance for end-users.

We could reconsider deprecating `deserializeState` though.
