### ISSUE TITLE
Any plans about compatibility with @ngrx/store ?

### ISSUE THREAD

**Issue by mildful** [zalmoxisus/redux-devtools-extension#77]
Hi.

I'm using [@ngrx/store](https://github.com/ngrx/store) to manage my Angular 2 application which is inspired by Redux.

I would like to know if redux-devtools-extension could be compatible with it ? I'm working on it but if someone already knows something about that and can help, it would be fine.

Thanks for this awesome tool :-)

**Comment by zalmoxisus** [comment]
Hey,

As it doesn't support store enhancers, only middlewares (and those aren't compatible with redux), it wouldn't be possible to use with Redux DevTools directly. 

You could create a bind as [for freezer](https://github.com/arqex/freezer-redux-devtools) or use [remotedev](https://github.com/zalmoxisus/remotedev).

In case you release a solution please let me know so I will add it to the README.

**Comment by mildful** [comment]
This tool already exists :
https://github.com/ngrx/devtools
https://twitter.com/robwormald/status/708907973796495360

**Comment by zalmoxisus** [comment]
Thanks for the info! Is there any example with Devtools ([the official example](https://github.com/ngrx/angular2-store-example) seems not to include it) so I could investigate it?

**Comment by mildful** [comment]
You can see an implementation of it here : https://plnkr.co/edit/46Sutu999iJ9SNN9xhyC?p=preview :-)

**Comment by zalmoxisus** [comment]
@mildful, thanks for the demo. The good news is that it uses the same data structure as Redux Devtools stores in `store.liftedStore` (you can get it from `this.store._backend.liftedState.value`), but `@ngrx/store` API is completely different from the Redux one.

I'm not too familiar with observables, if you want to try it to implement it, all you have to do is to replicate [the script the the extension uses to communicate with the page](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js). This script can be added in the page directly, and it will send and receive the changes. All you have to do is to replace `store.subscribe` with observables. Instead of `store.getState` and `store.liftedStore.getState`, you could read it directly from `store._value` and `this.store._backend.liftedState.value` (as I don't see similar functions in `@ngrx/store`). If you could implement that, we'll have the first step done - subscribing extensions monitors to the app's store changes. 

The main advantage of integrating it with the extension would be that you will be able use [the awesome Redux DevTools monitors](https://github.com/zalmoxisus/redux-devtools-extension#redux-devtools-extension).

**Comment by mildful** [comment]
@zalmoxisus thanks a lot. 
I'll try to do as soon as possible.

**Comment by johnhamm** [comment]
Any progress on this?  Although I have ngrx devtools working with my ng2 project, I would much rather use the extension for the awesome monitor capabilities and the ability to use with production builds.

**Comment by zalmoxisus** [comment]
We should first ask @MikeRyan52 if he would be interested to support the extension, otherwise any effort here will be broken with [new API changes in `ngrx/devtools`](https://github.com/gaearon/redux-devtools/pull/243#issuecomment-202218034).

**Comment by mildful** [comment]
Currently, I have a lot of work and I have not tried. Sorry !

**Comment by MikeRyan52** [comment]
@zalmoxisus I'm certainly interested in seeing if it is possible to add @ngrx/store support, but as you've already discovered the way the store is instrumented is very different from redux. The general problem is that we expose our store as an observable, so simply lifting the store's API doesn't really work.

With that being said, since the underlying wrapped state interface is the exact same it might be feasible to cast our lifted store to the redux store API:
```ts
function castToReduxAPI(tools: StoreDevtools) {
  return {
    getState() {
      return tools.liftedState.getValue();
    },
    dispatch(action) {
      tools.dispatch(action);
    },
    subscribe(listener) {
      const sub = tools.liftedState.subscribe(listener);

      return () => sub.unsubscribe();
    },
    replaceReducer(reducer) {
      tools.replaceReducer(reducer);
    }
  }
}
```

**Comment by zalmoxisus** [comment]
@MikeRyan52, thanks for the details. Actually, the extension is quite agnostic about the client's store. Redux Devtools with the monitors is on the background page. We just need to modify the injected script to relay the changes from `@ngrx/store` (with the same structure as for the liftedState) to the background script and have the ability to dispatch actions received from the background script inside `@ngrx/store`.

I'll try to refactor the injected script to have an universal API.

**Comment by zalmoxisus** [comment]
The extension has now an extended API to [communicate with it directly](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/API/Methods.md#windowdevtoolsextensionconnectconfig). So, it's easy to use it for any architecture. [Here's an example of usage](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/examples/react-counter-messaging/components/Counter.js). If someone could share an example of how to integrate it with `@ngrx/store` it would be very welcome.

**Comment by MikeRyan52** [comment]
I'll take a stab at it 👍

**Comment by MikeRyan52** [comment]
Ok, I got _very basic_ undo/redo working A few questions:

* What and when should I be sending to devToolsExtension.send() ? Lifted actions and lifted state?
* How do I keep the lifted state in sync with the monitors?
* `DISPATCH` actions coming from the extension should be funneled through the lifted reducer, right?

**Comment by zalmoxisus** [comment]
@MikeRyan52, sorry, I forgot about liftedState. Now instead of `send(action, state)` we can use also `send(null, liftedState)` (I'll the changes to Chrome store in few hours).

After `const devTools = window.devToolsExtension.connect()` better to use `devTools.send()` instead (it's [the same](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/utils/contentScriptMsg.js#L76), but we don't have to keep track of instance id).

Basically,  

```js
let isStarted = false;

const devTools = window.devToolsExtension.connect();
devTools.subscribe((message) => {
  if (message.type === 'START') {
    isStarted = true;
    devTools.send(null, store.liftedStore.getState());
  } else if (message.type === 'STOP') {
    isStarted = false;
  } else if (message.type === 'DISPATCH' && message.payload.type !== 'JUMP_TO_STATE') {
    store.liftedStore.dispatch(message.payload);
  } else if (message.type === 'ACTION') { // Received a store action from Dispatch monitor
    store.dispatch(message.payload);
  } 
});

store.subscribe(() => {
  if (!isStarted) return;
  const liftedState = store.liftedStore.getState();
  devTools.send(null, liftedState);
});
```

We could always send `liftedState` for any changes inside the store, and it should work, but this object can grow too big and it will affect the performance. So, it's better to use something like this:

```js
let isStarted = false;
let isLiftedAction = false;

const devTools = window.devToolsExtension.connect();
devTools.subscribe((message) => {
  if (message.type === 'START') {
    isStarted = true;
    devTools.send(null, store.liftedStore.getState());
  } else if (message.type === 'STOP') {
    isStarted = false;
  } else if (message.type === 'DISPATCH' && message.payload.type !== 'JUMP_TO_STATE') {
    isLiftedAction = true;
    store.liftedStore.dispatch(message.payload);
  } else if (message.type === 'ACTION') { // Received a store action from Dispatch monitor
    store.dispatch(message.payload);
  } 
});

store.subscribe(() => {
  if (!isStarted) return;
  const liftedState = store.liftedStore.getState();
  if (isLiftedAction) { devTools.send(null, liftedState); isLiftedAction = false; }
  else devTools.send(liftedState.actionsById[liftedState.nextActionId - 1], store.getState());
});
```
I didn't try the examples, will try to add a more complex example next days after the conference.

**Comment by MikeRyan52** [comment]
Sounds great. Here's a link to our example app with experimental support for the extension: http://ngrx.github.io/example-app/

**Comment by MikeRyan52** [comment]
@zalmoxisus Next release of ngrx/store-devtools will have full extension compatibility. Let's coordinate an announcement.

**Comment by zalmoxisus** [comment]
@MikeRyan52, that's awesome! I'll add it to the README.

**Comment by zalmoxisus** [comment]
Added also an [Integrations page](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md#angular-ngrxstore). Feel free to send a PR if any changes in the API occur.
