### ISSUE TITLE
Possible to insert my own monitor to the tools?

### ISSUE THREAD

**Issue by pke** [zalmoxisus/redux-devtools-extension#91]
I wonder if its possible to insert my own monitor to the extension. 
Could the extension be given a set of monitors in its options?

**Comment by zalmoxisus** [comment]
@pke, that's a good suggestion, I was thinking about. Unfortunately for Chrome extensions and apps it is not possible to implement a plugin system (as we'd do for an Electron app), though there are some workarounds, but they are not allowed and a lot of Chrome apps were banned on web store because of that.

Passing the monitor react component rendered to string via `react-dom/server` to the extension through a parameter probably would be possible. We need it as string because it will be sent from the injected script to the extension's script. If you're interested in this, we can continue investigation.

Of course the easiest way is to add the monitor in the code directly like [so](https://github.com/zalmoxisus/redux-devtools-extension/pull/64/commits/5b5916c7ca6ad8ef8bbf146ce362fe243ef1095a).

**Comment by pke** [comment]
Cool, I'll write my monitor for `react-ab-test` to select the active variants. Not really `redux` related but I like to have all those monitors in one place. Maybe `redux-devtools` should be renamed `react-devtools` eventually :)

At the moment I am struggling with an `Uncaught Invariant Violation: Must be mounted to trap events` when using the `DevTools.instrument()` call.
